//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocoholicsPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ap_period
    {
        public int APPeriodID { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
