//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocoholicsPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_info
    {
        public int BillID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<decimal> ExpectedCost { get; set; }
        public string Notes { get; set; }
    }
}
