//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocoholicsPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chocanonEntities : DbContext
    {
        public chocanonEntities()
            : base("name=chocanonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill_info> bill_info { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<provider> provider { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<@operator> @operator { get; set; }
    }
}
