//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocoholicsPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class eft
    {
        public int ProviderID { get; set; }
        public string ProviderName { get; set; }
        public double Amount { get; set; }
        public int APPeriodID { get; set; }
    
        public virtual provider provider { get; set; }
    }
}
